# theme: jekyll-theme-slate

# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

# Setup
title: Siyaofa
tagline:          'All is well'
description:      '娄尚 - 个人博客'
url:              https://lous.github.io
baseurl:          /

author:
  name:           'Siyaofa'
  url:            https://lous.github.io

paginate:         5
# markdown: kramdown
# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#       type: "posts" # previously `post` in Jekyll 2.2.
#     values:
#       layout: "post"
github:
  repo:           https://github.com/siyaofa
